name: draggable_panel_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter
  draggable_panel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 120
