// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:flutter/material.dart';

@immutable
class DraggablePanelButtonItem {
  const DraggablePanelButtonItem({
    required this.onTap,
    this.description,
    required this.label,
    required this.icon,
  });

  final IconData icon;
  final String? description;
  final String label;
  final void Function(BuildContext context) onTap;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is DraggablePanelButtonItem &&
        other.icon == icon &&
        other.description == description &&
        other.label == label &&
        other.onTap == onTap;
  }

  @override
  int get hashCode => Object.hash(icon, description, label, onTap);
}
