// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:flutter/material.dart';

@immutable
class DraggablePanelItem {
  const DraggablePanelItem({
    this.description,
    required this.onTap,
    required this.enableBadge,
    required this.icon,
  });

  final String? description;
  final IconData icon;
  final bool enableBadge;
  final void Function(BuildContext context) onTap;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is DraggablePanelItem &&
        other.description == description &&
        other.icon == icon &&
        other.enableBadge == enableBadge &&
        other.onTap == onTap;
  }

  @override
  int get hashCode {
    return description.hashCode ^
        icon.hashCode ^
        enableBadge.hashCode ^
        onTap.hashCode;
  }
}
