// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// `DraggablePanelTheme` defines the visual properties of the [DraggablePanel].
///
/// You can use this class to customize the appearance of the panel globally or
/// locally by passing it to the [DraggablePanel] widget.
@immutable
class DraggablePanelTheme {
  const DraggablePanelTheme({
    this.draggableButtonWidth = 35.0,
    this.draggableButtonHeight = 70.0,
    this.draggableButtonColor,
    this.panelBackgroundColor,
    this.panelBorder,
    this.panelBorderRadius = const BorderRadius.all(Radius.circular(16)),
    this.panelBoxShadow,
    this.panelItemColor,
    this.panelButtonColor,
    this.panelButtonIconColor,
    this.foregroundColor,
  });

  /// The width of the draggable button.
  final double draggableButtonWidth;

  /// The height of the draggable button.
  final double draggableButtonHeight;

  /// The background color of the draggable button.
  final Color? draggableButtonColor;

  /// The background color of the panel.
  final Color? panelBackgroundColor;

  /// The border of the panel.
  final BoxBorder? panelBorder;

  /// The border radius of the panel.
  final BorderRadiusGeometry panelBorderRadius;

  /// The shadow of the panel.
  final List<BoxShadow>? panelBoxShadow;

  /// The color of the items in the panel.
  final Color? panelItemColor;

  /// The background color of the buttons inside the panel.
  final Color? panelButtonColor;

  /// The color of the icons in the buttons inside the panel.
  final Color? panelButtonIconColor;

  /// The foreground color of the panel.
  /// For: icons, text, etc.
  final Color? foregroundColor;

  DraggablePanelTheme copyWith({
    double? draggableButtonWidth,
    double? draggableButtonHeight,
    Color? draggableButtonColor,
    Color? panelBackgroundColor,
    BoxBorder? panelBorder,
    BorderRadiusGeometry? panelBorderRadius,
    List<BoxShadow>? panelBoxShadow,
    Color? panelItemColor,
    Color? panelButtonColor,
    Color? panelButtonIconColor,
    Color? foregroundColor,
  }) {
    return DraggablePanelTheme(
      draggableButtonWidth: draggableButtonWidth ?? this.draggableButtonWidth,
      draggableButtonHeight:
          draggableButtonHeight ?? this.draggableButtonHeight,
      draggableButtonColor: draggableButtonColor ?? this.draggableButtonColor,
      panelBackgroundColor: panelBackgroundColor ?? this.panelBackgroundColor,
      panelBorder: panelBorder ?? this.panelBorder,
      panelBorderRadius: panelBorderRadius ?? this.panelBorderRadius,
      panelBoxShadow: panelBoxShadow ?? this.panelBoxShadow,
      panelItemColor: panelItemColor ?? this.panelItemColor,
      panelButtonColor: panelButtonColor ?? this.panelButtonColor,
      panelButtonIconColor: panelButtonIconColor ?? this.panelButtonIconColor,
      foregroundColor: foregroundColor ?? this.foregroundColor,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is DraggablePanelTheme &&
        other.draggableButtonWidth == draggableButtonWidth &&
        other.draggableButtonHeight == draggableButtonHeight &&
        other.draggableButtonColor == draggableButtonColor &&
        other.panelBackgroundColor == panelBackgroundColor &&
        other.panelBorder == panelBorder &&
        other.panelBorderRadius == panelBorderRadius &&
        listEquals(other.panelBoxShadow, panelBoxShadow) &&
        other.panelItemColor == panelItemColor &&
        other.panelButtonColor == panelButtonColor &&
        other.panelButtonIconColor == panelButtonIconColor &&
        other.foregroundColor == foregroundColor;
  }

  @override
  int get hashCode {
    return draggableButtonWidth.hashCode ^
        draggableButtonHeight.hashCode ^
        draggableButtonColor.hashCode ^
        panelBackgroundColor.hashCode ^
        panelBorder.hashCode ^
        panelBorderRadius.hashCode ^
        panelBoxShadow.hashCode ^
        panelItemColor.hashCode ^
        panelButtonColor.hashCode ^
        panelButtonIconColor.hashCode ^
        foregroundColor.hashCode;
  }
}
